Script started on Sat 19 Apr 2008 02:23:07 AM EDT
baccala@bigsky ~/DifAlg$ M23 
Macaulay 2, version 0.9.95
--warning: memory maps have changed, can't load cached data: /usr/lib/Macaulay2/Core/cache/Macaulay2-i686-data
with packages: Classic, Core, Elimination, IntegralClosure, LLLBases, Parsing,
               PrimaryDecomposition, SchurRings, TangentCone

i1 : Rx = QQ[x]

o1 = Rx

o1 : PolynomialRing

i2 : Fx = frac Rx

o2 = Fx

o2 : FractionField

i3 : diff(x,poly "x4               root = poly "x4+4x3+2x2+1"

      4     3     2
o3 = x  + 4x  + 2x  + 1

o3 : Fx

i4 : diff(x,root)
stdio:4:1:(1):[0]: expected a polynomial ring

i5 : Rx

o5 = Rx

o5 : PolynomialRing

i6 : Rxdiff(x,root)i6 : root = poly "x4+4x3+2x2+1"

      4     3     2
o6 = x  + 4x  + 2x  + 1

o6 : Fx

i7 : root = poly "x4+4x3+2x2+1"i7 :                           i7 : root = poly "x4+4x3+2x2+1"i7 : Rx                        i7 : RxuRxsRxeRx Rx

o7 = Rx

o7 : PolynomialRing

i8 : use Rxroot = poly "x4+4x3+2x2+1"

      4     3     2
o8 = x  + 4x  + 2x  + 1

o8 : Rx

i9 : root = poly "x4+4x3+2x2+1"i9 : use Rx                    i9 : use Rxroot = poly "x4+4x3+2x2+1"i9 : Rx                        i9 : Rxdiff(x,root)

       3      2
o9 = 4x  + 12x  + 4x

o9 : Rx

i10 : gcd(o9, root)

o10 = 1

o10 : Rx

i11 : Fxy = Fx[y]/(y^2-root)

o11 = Fxy

o11 : QuotientRing

i12 : diff(x,y)

o12 = x*y

o12 : Fxy

i13 : poly "2x3+6x2+2x" / root

          3     2
        2x  + 6x  + 2x
o13 = ------------------
       4     3     2
      x  + 4x  + 2x  + 1

o13 : Fx

i14 : x

o14 = x

o14 : Rx

i15 : use Fxy

o15 = Fxy

o15 : QuotientRing

i16 : use Fxyx      poly "2x3+6x2+2x" / rooti16 : diff(x,y)               

o16 = x*y

o16 : Fxy

i17 : y^2

       4     3     2
o17 = x  + 4x  + 2x  + 1

o17 : Fxy

i18 : root/2y
stdio:18:6:(1):[0]: no method for adjacent objects:
--            2 (of class ZZ)
--    SPACE   y (of class Fxy)

i19 : root/2y*y

       4     3     2
      x  + 4x  + 2x  + 1
o19 = ------------------*y
               2

o19 : Fxy

i20 : root/2*y(2*y2*y)

         4     3     2
      - x  - 4x  - 2x  - 1
      --------------------
               -2
o20 = --------------------
                y

o20 : frac(Fxy)

i21 : diff(x,root)

        3      2
o21 = 4x  + 12x  + 4x

o21 : Rx

i22 : diff(x,root)/2

        3      2
      4x  + 12x  + 4x
o22 = ---------------
             2

o22 : Fx

i23 : use Rx

o23 = Rx

o23 : PolynomialRing

i24 : use Rxdiff(x,root)/2

        3      2
      4x  + 12x  + 4x
o24 = ---------------
             2

o24 : Fx

i25 : diff(x,root)/2/2

        3     2
o25 = 2x  + 6x  + 2x

o25 : Rx

i26 : diff(x,root)//2i26 : (diff(x,root)//2i26 : (diff(x,root)//2 i26 : diff(x,root)//2/root

          3     2
        2x  + 6x  + 2x
o26 = ------------------
       4     3     2
      x  + 4x  + 2x  + 1

o26 : Fx

i27 : diff(x,root)//2/root*y

          3     2
        2x  + 6x  + 2x
o27 = ------------------*y
       4     3     2
      x  + 4x  + 2x  + 1

o27 : Fxy

i28 : diff(x,root)//2/root*yi28 : ydiff(x,root)//2/root*yi28 : ytdiff(x,root)//2/root*yi28 : ytidiff(x,root)//2/root*yi28 : yticdiff(x,root)//2/root*yi28 : ytic=diff(x,root)//2/root*yi28 : ytic=

          3     2
        2x  + 6x  + 2x
o28 = ------------------*y
       4     3     2
      x  + 4x  + 2x  + 1

o28 : Fxy

i29 : U = root

       4     3     2
o29 = x  + 4x  + 2x  + 1

o29 : Rx

i30 : V=poly"2   "2x2-1"

        2
o30 = 2x  - 1

o30 : Rx

i31 : U(V*ytic*(V*ytic(V*ytic - diff(V x,V)*y)

           4     3     2
o31 = (- 4x  - 6x  - 6x  - 6x)y

o31 : Fxy

i32 : U*(V*ytic - diff(x,V)*y)i32 : SU*(V*ytic - diff(x,V)*y)i32 : S2U*(V*ytic - diff(x,V)*y)i32 : S2=U*(V*ytic - diff(x,V)*y)i32 : S2=

           4     3     2
o32 = (- 4x  - 6x  - 6x  - 6x)y

o32 : Fxy

i33 : f2=   numerator=poly"  "2x6+4x5+7x4-3x3-x2-8x-8"
stdio:33:10:(1):[0]: assignment to protected variable 'numerator'

i34 : numerator=poly "2x6+4x5+7x4-3x3-x2-8x-8"i34 : numrator=poly "2x6+4x5+7x4-3x3-x2-8x-8" i34 : numator=poly "2x6+4x5+7x4-3x3-x2-8x-8" i34 : numtor=poly "2x6+4x5+7x4-3x3-x2-8x-8" i34 : numor=poly "2x6+4x5+7x4-3x3-x2-8x-8" i34 : numr=poly "2x6+4x5+7x4-3x3-x2-8x-8" i34 : num=poly "2x6+4x5+7x4-3x3-x2-8x-8" i34 : num=poly "2x6+4x5+7x4-3x3-x2-8x-8"

        6     5     4     3    2
o34 = 2x  + 4x  + 7x  - 3x  - x  - 8x - 8

o34 : Rx

i35 : f2=num/S2

          6     5     4     3    2
      - 2x  - 4x  - 7x  + 3x  + x  + 8x + 8
      -------------------------------------
                 4     3     2
               4x  + 6x  + 6x  + 6x
o35 = -------------------------------------
                        y

o35 : frac(Fxy)

i36 : f2=num/S2*y

          6      5      4      3     2
      - 8x  - 16x  - 28x  + 12x  + 4x  + 32x + 32
o36 = -------------------------------------------
                   4      3      2
                16x  + 24x  + 24x  + 24x

o36 : frac(Fxy)

i37 : f2=num/S2*y  

          6     5     4     3    2
      - 2x  - 4x  - 7x  + 3x  + x  + 8x + 8
      -------------------------------------
                 4     3     2
               4x  + 6x  + 6x  + 6x
o37 = -------------------------------------
                        y

o37 : frac(Fxy)

i38 : f2*y

          6      5      4      3     2
      - 8x  - 16x  - 28x  + 12x  + 4x  + 32x + 32
o38 = -------------------------------------------
                   4      3      2
                16x  + 24x  + 24x  + 24x

o38 : frac(Fxy)

i39 : f2*y/y^2(y^2y^2 y^2

                     6         5         4         3        2
              - 8192x  - 16384x  - 28672x  + 12288x  + 4096x  + 32768x + 32768
o39 = --------------------------------------------------------------------------
            8         7          6          5          4         3         2
      16384x  + 90112x  + 155648x  + 172032x  + 163840x  + 73728x  + 24576x  + 2
      --------------------------------------------------------------------------
      -----

      4576x

o39 : frac(Fxy)

i40 : f2*y/y^2i40 : (f2*y/y^2f2*y/y^2)*y

                                                     6                          
                       - 309485009821345068724781056x  - 61897001964269013744956
o40 = --------------------------------------------------------------------------
                                  8                                7            
      618970019642690137449562112x  + 3404335108034795755972591616x  + 588021518
      --------------------------------------------------------------------------
           5                                4                               3   
      2112x  - 1083197534374707740536733696x  + 464227514732017603087171584x  + 
      --------------------------------------------------------------------------
                          6                                5                    
      6605556305770840064x  + 6499185206248246443220402176x  + 61897001964269013
      --------------------------------------------------------------------------
                                  2
      154742504910672534362390528x  + 1237940039285380274899124224x + 1237940039
      --------------------------------------------------------------------------
                  4                                3                            
      74495621120x  + 2785365088392105618523029504x  + 9284550294640352061743431
      --------------------------------------------------------------------------
      285380274899124224
      -----------------------------------*y
         2
      68x  + 928455029464035206174343168x

o40 : frac(Fxy)

i41 : (f2*y/y^2)*yi41 : f2*y/y^2        

          6      5      4      3     2
      - 8x  - 16x  - 28x  + 12x  + 4x  + 32x + 32
o41 = -------------------------------------------
                   4      3      2
                16x  + 24x  + 24x  + 24x

o41 : frac(Fxy)

i42 : f2

          6     5     4     3    2
      - 2x  - 4x  - 7x  + 3x  + x  + 8x + 8
      -------------------------------------
                 4     3     2
               4x  + 6x  + 6x  + 6x
o42 = -------------------------------------
                        y

o42 : frac(Fxy)

i43 : f2*y

          6      5      4      3     2
      - 8x  - 16x  - 28x  + 12x  + 4x  + 32x + 32
o43 = -------------------------------------------
                   4      3      2
                16x  + 24x  + 24x  + 24x

o43 : frac(Fxy)

i44 : f2*y/8

             6         5         4         3        2
      - 8192x  - 16384x  - 28672x  + 12288x  + 4096x  + 32768x + 32768
o44 = ----------------------------------------------------------------
                         4          3          2
                  131072x  + 196608x  + 196608x  + 196608x

o44 : frac(Fxy)

i45 : f2*y/8  (f2*yf2*y)

          6      5      4      3     2
      - 8x  - 16x  - 28x  + 12x  + 4x  + 32x + 32
o45 = -------------------------------------------
                   4      3      2
                16x  + 24x  + 24x  + 24x

o45 : frac(Fxy)

i46 : (f2*y)/8

             6         5         4         3        2
      - 8192x  - 16384x  - 28672x  + 12288x  + 4096x  + 32768x + 32768
o46 = ----------------------------------------------------------------
                         4          3          2
                  131072x  + 196608x  + 196608x  + 196608x

o46 : frac(Fxy)

i47 : (f2*y)/8 4

             6         5         4         3        2
      - 8192x  - 16384x  - 28672x  + 12288x  + 4096x  + 32768x + 32768
o47 = ----------------------------------------------------------------
                          4         3         2
                    65536x  + 98304x  + 98304x  + 98304x

o47 : frac(Fxy)

i48 : (f2*y)/4 2

             6         5         4         3        2
      - 8192x  - 16384x  - 28672x  + 12288x  + 4096x  + 32768x + 32768
o48 = ----------------------------------------------------------------
                          4         3         2
                    32768x  + 49152x  + 49152x  + 49152x

o48 : frac(Fxy)

i49 : (f2*y)/2 1

             6         5         4         3        2
      - 8192x  - 16384x  - 28672x  + 12288x  + 4096x  + 32768x + 32768
o49 = ----------------------------------------------------------------
                          4         3         2
                    16384x  + 24576x  + 24576x  + 24576x

o49 : frac(Fxy)

i50 : (f2*y)/1   f2*y f2*y

          6      5      4      3     2
      - 8x  - 16x  - 28x  + 12x  + 4x  + 32x + 32
o50 = -------------------------------------------
                   4      3      2
                16x  + 24x  + 24x  + 24x

o50 : frac(Fxy)

i51 : factor(i o50)
stdio:51:1:(1):[0]: factor: unimplemented for this ring

i52 : simplify(o50)
stdio:52:1:(1):[0]: no method for adjacent objects:
--            simplify (of class Symbol)
--                6      5      4      3     2
--            - 8x  - 16x  - 28x  + 12x  + 4x  + 32x + 32
--    SPACE   ------------------------------------------- (of class frac(Fxy))
--                         4      3      2
--                      16x  + 24x  + 24x  + 24x

i53 : simplify(o50)i53 : simpify(o50) fy(o50) y(o50) (o50) 
stdio:53:1:(1):[0]: no method for adjacent objects:
--            simp (of class Symbol)
--                6      5      4      3     2
--            - 8x  - 16x  - 28x  + 12x  + 4x  + 32x + 32
--    SPACE   ------------------------------------------- (of class frac(Fxy))
--                         4      3      2
--                      16x  + 24x  + 24x  + 24x

i54 : 
baccala@bigsky ~/DifAlg$ exit

Script done on Sat 19 Apr 2008 02:31:36 PM EDT
